services:
  thamestracker:
    container_name: thamestracker
    image: ghcr.io/takenobou/thamestracker:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis

  redis:
    container_name: thamestracker-redis
    image: redis:latest
    ports:
      - "6379:6379"